### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by Diddle1** [W0rthlessS0ul/nRF24_jammer#1]
I have the 128 x 64 but i can't compile because of errors based on the RF24.h, I was wanting to change it to be able to try it. I flashed my esp32 and watched my serial monitor just go nuts. And make a slight change to the ssid because obviously that being aired on my network is just not feasible lol. If you don't have anyway around this i guess next week ill be rewriting a bunch.

Nevermind heres the fix: https://github.com/smoochiee/Bluetooth-jammer-esp32

**Comment by W0rthlessS0ul** [comment]
Hello! Could you please share the output from your serial monitor? Also, please note that all the bitmaps are designed for a 128x32 display, so it might be challenging to properly connect a 128x64 display. Thank you!
