### ISSUE TITLE
Error select channel

### ISSUE THREAD

**Issue by samukas81** [W0rthlessS0ul/nRF24_jammer#10]

**Comment by W0rthlessS0ul** [comment]
Please let me know how the error is occurring on your end, and if possible, could you send a video to w0rthlesss00ul@gmail.com?

**Comment by samukas81** [comment]
Hello, sorry for the delay in responding, it was my mistake, it works very well!

**Comment by W0rthlessS0ul** [comment]
Since there are no more problems, I consider this issue resolved.
