### ISSUE TITLE
Acess point

### ISSUE THREAD

**Issue by samukas81** [W0rthlessS0ul/nRF24_jammer#13]
Hello, is it possible to add a function to turn the access point on and off to hide ssid jammer?

**Comment by W0rthlessS0ul** [comment]
Hello again, my constant source of ideas! I think implementing something like this won’t be a difficult task, so thank you for your suggestion. Also, I will probably include you in the Acknowledgments section in the next update.

**Comment by samukas81** [comment]
Cool! If you need anything and I can help, just call!

**Comment by W0rthlessS0ul** [comment]
Your idea has been added, so this issue can be closed.
