### ISSUE TITLE
more buttons wiring 

### ISSUE THREAD

**Issue by God1vaibhav** [W0rthlessS0ul/nRF24_jammer#3]
only one bluetooth jammer button is given give more wifi ble and zigbee jammer buttons wiring details

**Comment by God1vaibhav** [comment]
for how many seconds can I hold for next and for select current item

**Comment by W0rthlessS0ul** [comment]
To select an item, simply press and hold for 1-2 seconds.

**Comment by W0rthlessS0ul** [comment]
To switch to the next item, simply click, and the menu element will change.

**Comment by God1vaibhav** [comment]
ok bro done and thank you for supporting but one question is how can I change starting interface and add mine 😅

**Comment by W0rthlessS0ul** [comment]
Depending on what you want to achieve, if you simply want to change the images, modify the bitmap.h file to include your own drawings at a size of 128x32 (or adjusted according to your display). Additionally, you can convert it to C++ using this service: ![img2cpp](https://javl.github.io/image2cpp/)

In another case, good luck! You'll have to decipher my code that I wrote a month ago, and to be honest, I’m not sure I’ll understand it myself anymore. 😅

**Comment by W0rthlessS0ul** [comment]
Here is the service: [https://javl.github.io/image2cpp/](https://javl.github.io/image2cpp/)

**Comment by W0rthlessS0ul** [comment]
I believe we can conclude this issue, do you agree?
