### ISSUE TITLE
help in another project 

### ISSUE THREAD

**Issue by God1vaibhav** [W0rthlessS0ul/nRF24_jammer#4]
I need little more help in another project RFID cloner I was unable to make tell if you have any of RFID cloner using rc522

**Comment by W0rthlessS0ul** [comment]
Hello! Unfortunately, I didn’t use similar modules before. I was interested in buying the PN532 (which is also an NFC and RFID module, but smaller). However, after purchasing the Flipper Zero, I found that I no longer needed it.

**Comment by W0rthlessS0ul** [comment]
The only way I can help is by saying good luck!
