### ISSUE TITLE
Copyright Infridgement

### ISSUE THREAD

**Issue by EmenstaNougat** [W0rthlessS0ul/nRF24_jammer#6]
Copied parts of repository such as pinouts and inspiration/idea without credits.

https://github.com/EmenstaNougat/ESP32-BlueJammer

![image](https://github.com/user-attachments/assets/6c1716d0-95e0-443c-af37-abfdc9d7e065)

1:1 GPIO pinout as my ESP32-BlueJammer? This can't be a coincidence ;)

Jamming drones? Referred to my RC?

![image](https://github.com/user-attachments/assets/5cea0a53-4bce-47a8-922d-476dcb335d50)

**Comment by W0rthlessS0ul** [comment]
Hello, I’m afraid I was inspired not by your code, but rather by the code from this repository: https://github.com/smoochiee/Bluetooth-jammer-esp32.

**Comment by W0rthlessS0ul** [comment]
By the way, thank you for reminding me to credit the author; I'll make sure to cite smoochiee right away.

**Comment by EmenstaNougat** [comment]
Yeah, but I don't see my GPIO pinouts anywhere on smoochies repo

Am Do., 14. Nov. 2024 um 16:29 Uhr schrieb W0rthlessS0ul <
***@***.***>:

**Comment by W0rthlessS0ul** [comment]
I could have credited you in the Acknowledgments section if I had taken a part of your code. However, I cannot include you simply for the similar tables we created.

**Comment by W0rthlessS0ul** [comment]
Can we consider this issue resolved?

**Comment by EmenstaNougat** [comment]
Sure

W0rthlessS0ul ***@***.***> schrieb am Sa., 16. Nov. 2024,
08:38:

**Comment by smoochiee** [comment]
> I could have credited you in the Acknowledgments section if I had taken a part of your code. However, I cannot include you simply for the similar tables we created.

lol...why he think my repo dont have gpio pin out..🤔when its clearly there and he built my work before he started his...😂.shame

**Comment by W0rthlessS0ul** [comment]
Who knew GPIO pinouts could spark such intense discussions? 😂 Next thing you know, we’ll be debating who invented the wheel!

Since Smoochiee released his work on March 6, 2024, and you posted yours later on July 7, 2024, and considering that your repository isn't open source, I can assert that you used Smoochiee's code when creating your repository. 

So, I hope this clarifies things, and we won’t need to revisit this topic again!

**Comment by EmenstaNougat** [comment]
I'm not about the jammer stuff

smoochiee ***@***.***> schrieb am Do., 28. Nov. 2024, 12:49:
