### ISSUE TITLE
Wifi channel

### ISSUE THREAD

**Issue by samukas81** [W0rthlessS0ul/nRF24_jammer#9]
Could you implement specific wifi channel selection to deauthenticate?

**Comment by W0rthlessS0ul** [comment]
Hello, that's an interesting idea! I'll do my best to implement it in the next update.

**Comment by samukas81** [comment]
Doing more tests, I discovered that in all modes after reset it still sends some kind of signal. Only when it turns off does it stop, but in Bluetooth mode after reset it stops the interference. Sorry for the video quality, I had to reduce the size to be able to post.

https://github.com/user-attachments/assets/ec3fee8d-7ae8-421b-9104-4eff3395272c

**Comment by W0rthlessS0ul** [comment]
I'm not sure why, but the video you sent is opening as an MP3 file. Could you please create a repository and upload your video there so that I can watch it?

**Comment by samukas81** [comment]
download the vídeo

**Comment by samukas81** [comment]
Did you manage to watch the video?

**Comment by W0rthlessS0ul** [comment]
I'm a little busy right now, sorry I can't take a look.

**Comment by samukas81** [comment]
Don't worry, if you can't see it, let me know later, hugs.

**Comment by W0rthlessS0ul** [comment]
I have a little bit of free time, but I might be unavailable again soon. I’m having trouble downloading your video. If it's not too much trouble, could you please send it to my email: [w0rthlesss00ul@gmail.com](mailto:w0rthlesss00ul@gmail.com)? Thank you!

**Comment by W0rthlessS0ul** [comment]
An access point is being created on the ESP32, which also operates within the 2400 MHz to 2500 MHz range. However, my device does not transmit that much data, so either you are using an ESP32 with a more powerful transmitter (though that's unlikely), or there are issues with connecting the NRF24. It is definitely not a software issue, as the NRF24 is initialized only after the attack is launched.

**Comment by samukas81** [comment]
How do I disable this access point that it creates, which lines do I disable in the sketch?

**Comment by W0rthlessS0ul** [comment]
Please insert the following code into the nRF24_jammer.ino file:
#include "SPI.h"
#include "Update.h"
#include "EEPROM.h"
#include "Adafruit_GFX.h"
#include "Adafruit_SSD1306.h"
#include "GyverButton.h"
#include "RF24.h"
#include "bitmap.h"
#include "html.h"
#include "WiFi.h"
#include "WebServer.h"
#include "options.h"
#include "jam.h"

void handleRoot() {
    server.send(200, "text/html", html);
}

void sendHtmlAndExecute(const char* htmlResponse, void (*action)() = nullptr) {
    server.send(200, "text/html", htmlResponse);
    if (action) action();
}

void jamHandler(const char* htmlResponse, void (*jamFunction)()) {
    sendHtmlAndExecute(htmlResponse, jamFunction);
}

void miscChannelsHandler() {
    int channel1 = server.arg("start").toInt();
    int channel2 = server.arg("stop").toInt();
    sendHtmlAndExecute(html_misc_jam);
    misc_jam(channel1, channel2);
}

void settingsHandler(const char* htmlResponse) {
    sendHtmlAndExecute(htmlResponse);
}

void storeEEPROMAndSet(int index, int value, int& targetVar) {
    EEPROM.write(index, value);
    EEPROM.commit();
    targetVar = value;
    sendHtmlAndExecute(html);
}

void registerRoute(const char* path, void (*handler)()) {
    server.on(path, handler);
}

void handleFileUpload() {
    HTTPUpload &upload = server.upload();
    static unsigned long lastUpdate = 0; 
    const unsigned long updateInterval = 100;

    if (upload.status == UPLOAD_FILE_START) {
        Serial.printf("Update: %s\n", upload.filename.c_str());
        if (!Update.begin(UPDATE_SIZE_UNKNOWN)) {
            Update.printError(Serial);
            server.send(200, "text/plain", "Update Failed");
            return;
        } else {
            server.sendContent(html_upload_progress);
            lastUpdate = millis();
        }
    } 
    else if (upload.status == UPLOAD_FILE_WRITE) {
        if (Update.write(upload.buf, upload.currentSize) != upload.currentSize) {
            Update.printError(Serial);
        }

        if (millis() - lastUpdate >= updateInterval) {
            lastUpdate = millis();
            int progress = (100.0 * Update.progress() / Update.size());
            server.sendContent(String("<script>updateProgress(") + progress + ");</script>");
        }
    } 
    else if (upload.status == UPLOAD_FILE_END) {
        if (Update.end(true)) {
            Serial.printf("Update Success: %u bytes\n", upload.totalSize);
            server.sendContent(String("<script>updateProgress(100); document.getElementById('status').innerHTML = 'Update Success';</script>"));
            delay(2000);
            ESP.restart();
        } else {
            Update.printError(Serial);
            server.sendContent("<script>document.getElementById('status').innerHTML = 'Update Failed';</script>");
        }
    }
}

void misc() {
    auto display_info = [&](String info) {
        display.clearDisplay();
        display.setCursor(0, 0);
        display.println("Start");
        display.setCursor(96, 0);
        display.println("Stop");
        display.setCursor(52, 0);
        display.println("Width");
        display.setCursor(8, 10);
        display.println(String(channel1));
        display.setCursor(60, 10);
        display.println(String(channel2 - channel1));
        display.setCursor(100, 10);
        display.println(String(channel2));
        display.setCursor(0, 20);
        display.println(info);
        display.display();
    };

    display.setTextColor(WHITE);
    display.setTextSize(1);
    display_info("");

    auto incrementChannel = [&](int& channel) {
        channel++;
        if (channel > 125) {
            channel = 0;
        }
    };

    while (true) {
        butt1.tick();

        if (butt1.isSingle() || butt1.isHold()) {
            if (butt1.isHold()) {
                delay(100);
            }
            incrementChannel(flag == 0 ? channel1 : channel2);
            display_info("");
        } 
        else if (butt1.isDouble()) {
            if (flag == 0) {
                flag = 1;
            } 
            else {
                if (channel1 > channel2) {
                    display_info("Error: Second < First");
                    flag = 0;
                }
                else {
                    display_info("Jamming Started");
                    misc_jam(channel1, channel2);
                }
            }
        }
    }
}

void setup() {
    Serial.begin(115200);
    EEPROM.begin(EEPROM_SIZE);

    // Initialize EEPROM values if unset
    for (int i = 0; i < 8; ++i) {
        if (EEPROM.read(i) == 255) {
            EEPROM.write(i, 0);
            EEPROM.commit();
        }
    }

    // Load settings
    bluetooth_jam_method = EEPROM.read(0);
    drone_jam_method = EEPROM.read(1);
    ble_jam_method = EEPROM.read(2);
    wifi_jam_method = EEPROM.read(3);
    Separate_or_together = EEPROM.read(4);
    zigbee_jam_method = EEPROM.read(5);
    misc_jam_method = EEPROM.read(6);
    logo = EEPROM.read(7);
    butt1.setTimeout(200);
    display.begin(SSD1306_SWITCHCAPVCC, 0x3C);
    if (logo == 0){
        display.clearDisplay();
        display.drawBitmap(0, 0, bitmap_logo, 128, 64, WHITE);
        display.display();
        delay(2000);
    }
    display.clearDisplay();
    display.drawBitmap(0, 0, bitmap_bluetooth_jammer, 128, 64, WHITE);
    display.display();
}

void loop() {
    butt1.tick();
    if (butt1.isSingle()) {
        menu_number = (menu_number + 1) % 6;
        display.clearDisplay();
        const uint8_t* bitmap = (menu_number == 0) ? bitmap_bluetooth_jammer :
                                (menu_number == 1) ? bitmap_drone_jammer :
                                (menu_number == 2) ? bitmap_wifi_jammer : 
                                (menu_number == 3) ? bitmap_ble_jammer : 
                                (menu_number == 4) ? bitmap_zigbee_jammer : bitmap_misc_jammer;
        display.drawBitmap(0, 0, bitmap, 128, 64, WHITE);
        display.display();
    }
    
    if (butt1.isHolded()) {
        if (menu_number == 5){
          misc();
        }
        display.clearDisplay();
        const uint8_t* bitmap = (menu_number == 0) ? bitmap_bluetooth_jam :
                                (menu_number == 1) ? bitmap_drone_jam :
                                (menu_number == 2) ? bitmap_wifi_jam : 
                                (menu_number == 3) ? bitmap_ble_jam : bitmap_zigbee_jam;
        display.drawBitmap(0, 0, bitmap, 128, 64, WHITE);
        display.display();
        
        switch (menu_number) {
            case 0: bluetooth_jam(); break;
            case 1: drone_jam(); break;
            case 2: wifi_jam(); break;
            case 3: ble_jam(); break;
            case 4: zigbee_jam(); break;
        }
    }
}

**Comment by W0rthlessS0ul** [comment]
Please insert the following code into the nRF24_jammer.ino file:
```#include "SPI.h"
#include "Update.h"
#include "EEPROM.h"
#include "Adafruit_GFX.h"
#include "Adafruit_SSD1306.h"
#include "GyverButton.h"
#include "RF24.h"
#include "bitmap.h"
#include "html.h"
#include "WiFi.h"
#include "WebServer.h"
#include "options.h"
#include "jam.h"

void handleRoot() {
    server.send(200, "text/html", html);
}

void sendHtmlAndExecute(const char* htmlResponse, void (*action)() = nullptr) {
    server.send(200, "text/html", htmlResponse);
    if (action) action();
}

void jamHandler(const char* htmlResponse, void (*jamFunction)()) {
    sendHtmlAndExecute(htmlResponse, jamFunction);
}

void miscChannelsHandler() {
    int channel1 = server.arg("start").toInt();
    int channel2 = server.arg("stop").toInt();
    sendHtmlAndExecute(html_misc_jam);
    misc_jam(channel1, channel2);
}

void settingsHandler(const char* htmlResponse) {
    sendHtmlAndExecute(htmlResponse);
}

void storeEEPROMAndSet(int index, int value, int& targetVar) {
    EEPROM.write(index, value);
    EEPROM.commit();
    targetVar = value;
    sendHtmlAndExecute(html);
}

void registerRoute(const char* path, void (*handler)()) {
    server.on(path, handler);
}

void handleFileUpload() {
    HTTPUpload &upload = server.upload();
    static unsigned long lastUpdate = 0; 
    const unsigned long updateInterval = 100;

    if (upload.status == UPLOAD_FILE_START) {
        Serial.printf("Update: %s\n", upload.filename.c_str());
        if (!Update.begin(UPDATE_SIZE_UNKNOWN)) {
            Update.printError(Serial);
            server.send(200, "text/plain", "Update Failed");
            return;
        } else {
            server.sendContent(html_upload_progress);
            lastUpdate = millis();
        }
    } 
    else if (upload.status == UPLOAD_FILE_WRITE) {
        if (Update.write(upload.buf, upload.currentSize) != upload.currentSize) {
            Update.printError(Serial);
        }

        if (millis() - lastUpdate >= updateInterval) {
            lastUpdate = millis();
            int progress = (100.0 * Update.progress() / Update.size());
            server.sendContent(String("<script>updateProgress(") + progress + ");</script>");
        }
    } 
    else if (upload.status == UPLOAD_FILE_END) {
        if (Update.end(true)) {
            Serial.printf("Update Success: %u bytes\n", upload.totalSize);
            server.sendContent(String("<script>updateProgress(100); document.getElementById('status').innerHTML = 'Update Success';</script>"));
            delay(2000);
            ESP.restart();
        } else {
            Update.printError(Serial);
            server.sendContent("<script>document.getElementById('status').innerHTML = 'Update Failed';</script>");
        }
    }
}

void misc() {
    auto display_info = [&](String info) {
        display.clearDisplay();
        display.setCursor(0, 0);
        display.println("Start");
        display.setCursor(96, 0);
        display.println("Stop");
        display.setCursor(52, 0);
        display.println("Width");
        display.setCursor(8, 10);
        display.println(String(channel1));
        display.setCursor(60, 10);
        display.println(String(channel2 - channel1));
        display.setCursor(100, 10);
        display.println(String(channel2));
        display.setCursor(0, 20);
        display.println(info);
        display.display();
    };

    display.setTextColor(WHITE);
    display.setTextSize(1);
    display_info("");

    auto incrementChannel = [&](int& channel) {
        channel++;
        if (channel > 125) {
            channel = 0;
        }
    };

    while (true) {
        butt1.tick();

        if (butt1.isSingle() || butt1.isHold()) {
            if (butt1.isHold()) {
                delay(100);
            }
            incrementChannel(flag == 0 ? channel1 : channel2);
            display_info("");
        } 
        else if (butt1.isDouble()) {
            if (flag == 0) {
                flag = 1;
            } 
            else {
                if (channel1 > channel2) {
                    display_info("Error: Second < First");
                    flag = 0;
                }
                else {
                    display_info("Jamming Started");
                    misc_jam(channel1, channel2);
                }
            }
        }
    }
}

void setup() {
    Serial.begin(115200);
    EEPROM.begin(EEPROM_SIZE);

    // Initialize EEPROM values if unset
    for (int i = 0; i < 8; ++i) {
        if (EEPROM.read(i) == 255) {
            EEPROM.write(i, 0);
            EEPROM.commit();
        }
    }

    // Load settings
    bluetooth_jam_method = EEPROM.read(0);
    drone_jam_method = EEPROM.read(1);
    ble_jam_method = EEPROM.read(2);
    wifi_jam_method = EEPROM.read(3);
    Separate_or_together = EEPROM.read(4);
    zigbee_jam_method = EEPROM.read(5);
    misc_jam_method = EEPROM.read(6);
    logo = EEPROM.read(7);
    butt1.setTimeout(200);
    display.begin(SSD1306_SWITCHCAPVCC, 0x3C);
    if (logo == 0){
        display.clearDisplay();
        display.drawBitmap(0, 0, bitmap_logo, 128, 64, WHITE);
        display.display();
        delay(2000);
    }
    display.clearDisplay();
    display.drawBitmap(0, 0, bitmap_bluetooth_jammer, 128, 64, WHITE);
    display.display();
}

void loop() {
    butt1.tick();
    if (butt1.isSingle()) {
        menu_number = (menu_number + 1) % 6;
        display.clearDisplay();
        const uint8_t* bitmap = (menu_number == 0) ? bitmap_bluetooth_jammer :
                                (menu_number == 1) ? bitmap_drone_jammer :
                                (menu_number == 2) ? bitmap_wifi_jammer : 
                                (menu_number == 3) ? bitmap_ble_jammer : 
                                (menu_number == 4) ? bitmap_zigbee_jammer : bitmap_misc_jammer;
        display.drawBitmap(0, 0, bitmap, 128, 64, WHITE);
        display.display();
    }
    
    if (butt1.isHolded()) {
        if (menu_number == 5){
          misc();
        }
        display.clearDisplay();
        const uint8_t* bitmap = (menu_number == 0) ? bitmap_bluetooth_jam :
                                (menu_number == 1) ? bitmap_drone_jam :
                                (menu_number == 2) ? bitmap_wifi_jam : 
                                (menu_number == 3) ? bitmap_ble_jam : bitmap_zigbee_jam;
        display.drawBitmap(0, 0, bitmap, 128, 64, WHITE);
        display.display();
        
        switch (menu_number) {
            case 0: bluetooth_jam(); break;
            case 1: drone_jam(); break;
            case 2: wifi_jam(); break;
            case 3: ble_jam(); break;
            case 4: zigbee_jam(); break;
        }
    }
}```

**Comment by samukas81** [comment]
Does not compile

**Comment by W0rthlessS0ul** [comment]
[nRF24_jammer.zip](https://github.com/user-attachments/files/17968532/nRF24_jammer.zip)
Install all the .bin files from the ZIP archive above onto your ESP32.

**Comment by W0rthlessS0ul** [comment]
> Could you implement specific wifi channel selection to deauthenticate?

Your idea has been successfully implemented, so we can consider the issue resolved. Do you agree?

**Comment by samukas81** [comment]
yes

**Comment by W0rthlessS0ul** [comment]
Good luck! If you have any more ideas to contribute, feel free to create additional issues and share your suggestions there.

**Comment by samukas81** [comment]
Congratulations on your commitment!!

**Comment by W0rthlessS0ul** [comment]
Thank you! I appreciate your support and feedback. It motivates me to keep improving the project!
